import type { BowtieDiagram } from './types';

/**
 * Sample car accident bowtie diagram with hierarchical hazards
 */
export const carAccidentBowtie: BowtieDiagram = {
  id: 'car-accident-1',
  name: 'Car Accident Risk Analysis',
  hazard: {
    id: 'hazard-vehicle-highway',
    label: 'Driving a commercial vehicle on a highway',
    description:
      'Operating a loaded commercial vehicle on a public highway with mixed traffic and changing weather conditions.',
  },
  topEvent: {
    id: 'top-event-1',
    label: 'Vehicle Collision',
    description: 'A collision between vehicles or with obstacles',
    severity: 'critical',
  },
  threats: [
    {
      id: 'threat-1',
      label: 'Driver Error',
      description: 'Mistakes made by the driver',
      level: 0,
      severity: 'high',
      subThreats: [
        {
          id: 'threat-1-1',
          label: 'Distracted Driving',
          description: 'Using phone, eating, etc.',
          level: 1,
          parentId: 'threat-1',
          severity: 'high',
          subThreats: [
            {
              id: 'threat-1-1-1',
              label: 'Mobile Phone Use',
              level: 2,
              parentId: 'threat-1-1',
              severity: 'high',
            },
            {
              id: 'threat-1-1-2',
              label: 'Eating While Driving',
              level: 2,
              parentId: 'threat-1-1',
              severity: 'medium',
            },
          ],
        },
        {
          id: 'threat-1-2',
          label: 'Fatigue',
          description: 'Driver is tired or drowsy',
          level: 1,
          parentId: 'threat-1',
          severity: 'high',
        },
        {
          id: 'threat-1-3',
          label: 'Impaired Driving',
          description: 'Under influence of alcohol or drugs',
          level: 1,
          parentId: 'threat-1',
          severity: 'critical',
        },
        {
          id: 'threat-1-4',
          label: 'Speeding',
          description: 'Exceeding speed limits',
          level: 1,
          parentId: 'threat-1',
          severity: 'high',
        },
      ],
    },
    {
      id: 'threat-2',
      label: 'Vehicle Malfunction',
      description: 'Mechanical or electrical failures',
      level: 0,
      severity: 'medium',
      subThreats: [
        {
          id: 'threat-2-1',
          label: 'Brake Failure',
          level: 1,
          parentId: 'threat-2',
          severity: 'critical',
        },
        {
          id: 'threat-2-2',
          label: 'Tire Blowout',
          level: 1,
          parentId: 'threat-2',
          severity: 'high',
        },
        {
          id: 'threat-2-3',
          label: 'Steering Failure',
          level: 1,
          parentId: 'threat-2',
          severity: 'critical',
        },
      ],
    },
    {
      id: 'threat-3',
      label: 'Environmental Conditions',
      description: 'Weather and road conditions',
      level: 0,
      severity: 'medium',
      subThreats: [
        {
          id: 'threat-3-1',
          label: 'Poor Weather',
          level: 1,
          parentId: 'threat-3',
          severity: 'medium',
          subThreats: [
            {
              id: 'threat-3-1-1',
              label: 'Rain',
              level: 2,
              parentId: 'threat-3-1',
              severity: 'medium',
            },
            {
              id: 'threat-3-1-2',
              label: 'Snow/Ice',
              level: 2,
              parentId: 'threat-3-1',
              severity: 'high',
            },
            {
              id: 'threat-3-1-3',
              label: 'Fog',
              level: 2,
              parentId: 'threat-3-1',
              severity: 'medium',
            },
          ],
        },
        {
          id: 'threat-3-2',
          label: 'Poor Road Conditions',
          level: 1,
          parentId: 'threat-3',
          severity: 'medium',
        },
        {
          id: 'threat-3-3',
          label: 'Low Visibility',
          level: 1,
          parentId: 'threat-3',
          severity: 'medium',
        },
      ],
    },
    {
      id: 'threat-4',
      label: 'Other Road Users',
      description: 'Actions of pedestrians, cyclists, other drivers',
      level: 0,
      severity: 'medium',
      subThreats: [
        {
          id: 'threat-4-1',
          label: 'Pedestrian Error',
          level: 1,
          parentId: 'threat-4',
          severity: 'medium',
        },
        {
          id: 'threat-4-2',
          label: 'Other Driver Error',
          level: 1,
          parentId: 'threat-4',
          severity: 'high',
        },
      ],
    },
  ],
  consequences: [
    {
      id: 'consequence-1',
      label: 'Property Damage',
      description: 'Damage to vehicles and property',
      level: 0,
      severity: 'medium',
      subConsequences: [
        {
          id: 'consequence-1-1',
          label: 'Vehicle Damage',
          level: 1,
          parentId: 'consequence-1',
          severity: 'medium',
        },
        {
          id: 'consequence-1-2',
          label: 'Infrastructure Damage',
          level: 1,
          parentId: 'consequence-1',
          severity: 'low',
        },
      ],
    },
    {
      id: 'consequence-2',
      label: 'Injury',
      description: 'Physical harm to persons',
      level: 0,
      severity: 'high',
      subConsequences: [
        {
          id: 'consequence-2-1',
          label: 'Minor Injury',
          level: 1,
          parentId: 'consequence-2',
          severity: 'medium',
        },
        {
          id: 'consequence-2-2',
          label: 'Serious Injury',
          level: 1,
          parentId: 'consequence-2',
          severity: 'high',
        },
        {
          id: 'consequence-2-3',
          label: 'Fatal Injury',
          level: 1,
          parentId: 'consequence-2',
          severity: 'critical',
        },
      ],
    },
    {
      id: 'consequence-3',
      label: 'Traffic Disruption',
      description: 'Impact on traffic flow',
      level: 0,
      severity: 'low',
    },
    {
      id: 'consequence-4',
      label: 'Environmental Impact',
      description: 'Fuel spills, emissions',
      level: 0,
      severity: 'low',
    },
  ],
  barriers: [
    // Preventive barriers (left side)
    {
      id: 'barrier-1',
      label: 'Driver Training',
      description: 'Comprehensive driver education',
      type: 'preventive',
      effectiveness: 'high',
      threatId: 'threat-1',
      mechanism: 'activeHuman',
      owner: 'Training Lead',
    },
    {
      id: 'barrier-2',
      label: 'Traffic Laws Enforcement',
      type: 'preventive',
      effectiveness: 'high',
      threatId: 'threat-1',
      mechanism: 'activeHuman',
      owner: 'Compliance Officer',
    },
    {
      id: 'barrier-3',
      label: 'Vehicle Maintenance',
      type: 'preventive',
      effectiveness: 'high',
      threatId: 'threat-2',
      mechanism: 'activeHardware',
      owner: 'Maintenance Manager',
    },
    {
      id: 'barrier-4',
      label: 'Regular Inspections',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-2',
      mechanism: 'activeHuman',
      owner: 'Inspection Lead',
    },
    {
      id: 'barrier-5',
      label: 'Weather Monitoring',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-3',
      mechanism: 'activeHuman',
      owner: 'Dispatch Supervisor',
    },
    {
      id: 'barrier-6',
      label: 'Road Maintenance',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-3',
      mechanism: 'passiveHardware',
      owner: 'Infrastructure Manager',
    },
    {
      id: 'barrier-7',
      label: 'Traffic Signs & Signals',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-4',
      mechanism: 'passiveHardware',
      owner: 'City Traffic Engineer',
    },
    // Mitigative barriers (right side)
    {
      id: 'barrier-8',
      label: 'Seatbelts',
      type: 'mitigative',
      effectiveness: 'high',
      consequenceId: 'consequence-2',
      mechanism: 'activeHardware',
      owner: 'Fleet Safety Manager',
    },
    {
      id: 'barrier-9',
      label: 'Airbags',
      type: 'mitigative',
      effectiveness: 'high',
      consequenceId: 'consequence-2',
      mechanism: 'activeHardware',
      owner: 'Vehicle Engineering',
    },
    {
      id: 'barrier-10',
      label: 'Emergency Response',
      type: 'mitigative',
      effectiveness: 'high',
      consequenceId: 'consequence-2',
      mechanism: 'hybrid',
      owner: 'Emergency Coordinator',
    },
    {
      id: 'barrier-11',
      label: 'Insurance Coverage',
      type: 'mitigative',
      effectiveness: 'medium',
      consequenceId: 'consequence-1',
      mechanism: 'activeHuman',
      owner: 'Risk Manager',
    },
    {
      id: 'barrier-12',
      label: 'Traffic Management',
      type: 'mitigative',
      effectiveness: 'medium',
      consequenceId: 'consequence-3',
      mechanism: 'activeHuman',
      owner: 'Traffic Control Lead',
    },
  ],
};

