import type { BowtieDiagram } from './types';

export const lossOfControlScenario: BowtieDiagram = {
  id: 'loss-of-control-scenario',
  name: 'Commercial Vehicle Loss of Control',
  hazard: {
    id: 'hazard-commercial-highway',
    label: 'Driving a commercial vehicle on a highway',
    description: 'Operating a loaded commercial vehicle on a public highway.',
  },
  topEvent: {
    id: 'top-event-loss-of-control',
    label: 'Loss of control over the vehicle at 70 mph',
    description: 'Vehicle deviates from intended path at highway speed.',
    severity: 'high',
  },
  threats: [
    {
      id: 'threat-intoxicated-driving',
      label: 'Intoxicated driving',
      description: 'Driver operates while impaired by alcohol or drugs.',
      level: 0,
      severity: 'critical',
    },
    {
      id: 'threat-distractive-driving',
      label: 'Distractive driving',
      description: 'Use of mobile devices or other distractions.',
      level: 0,
      severity: 'high',
    },
    {
      id: 'threat-slippery-road',
      label: 'Driving on slippery road',
      description: 'Wet, icy, or debris-covered surfaces reduce traction.',
      level: 0,
      severity: 'medium',
    },
    {
      id: 'threat-poor-visibility',
      label: 'Driving with poor visibility',
      description: 'Fog, heavy rain, or nighttime glare reduces sight distance.',
      level: 0,
      severity: 'medium',
    },
  ],
  consequences: [
    {
      id: 'consequence-fixed-object',
      label: 'Crash into a fixed object',
      description: 'Collision with barriers, poles, or infrastructure.',
      level: 0,
      severity: 'high',
    },
    {
      id: 'consequence-internal-impact',
      label: 'Driver impacts internals of the vehicle',
      description: 'Occupants strike dashboard, steering wheel, or cabin walls.',
      level: 0,
      severity: 'high',
    },
    {
      id: 'consequence-rollover',
      label: 'Vehicle roll-over',
      description: 'Vehicle overturns due to loss of stability.',
      level: 0,
      severity: 'critical',
    },
  ],
  barriers: [
    {
      id: 'barrier-driver-self-report',
      label: 'Driver self-reports impairment',
      description: 'Supervisor replaces impaired driver before departure.',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-intoxicated-driving',
    },
    {
      id: 'barrier-dispatch-detects',
      label: 'Dispatcher detects impairment',
      description: 'Operations manager removes impaired driver from duty.',
      type: 'preventive',
      effectiveness: 'high',
      threatId: 'threat-intoxicated-driving',
    },
    {
      id: 'barrier-ignition-interlock',
      label: 'Ignition interlock device',
      description: 'Breath-enabled lock prevents impaired driver from starting vehicle.',
      type: 'preventive',
      effectiveness: 'high',
      threatId: 'threat-intoxicated-driving',
    },
    {
      id: 'barrier-lane-departure-warning',
      label: 'Lane departure warning assist',
      description: 'Active hardware alerts driver to drift and keeps lane discipline.',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-intoxicated-driving',
    },
    {
      id: 'barrier-driver-coaching',
      label: 'Driver coaching program',
      description: 'Behavioral training to minimize distraction behind the wheel.',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-distractive-driving',
    },
    {
      id: 'barrier-road-condition-monitoring',
      label: 'Road condition monitoring',
      description: 'Fleet dispatch updates drivers about slippery segments.',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-slippery-road',
    },
    {
      id: 'barrier-visibility-procedures',
      label: 'Low-visibility procedure',
      description: 'Reduced speed and escort rules for fog/heavy rain.',
      type: 'preventive',
      effectiveness: 'medium',
      threatId: 'threat-poor-visibility',
    },
    {
      id: 'barrier-seatbelts',
      label: 'Seatbelt policy',
      description: 'Verified seatbelt use before rolling to mitigate occupant injury.',
      type: 'mitigative',
      effectiveness: 'high',
      consequenceId: 'consequence-internal-impact',
    },
    {
      id: 'barrier-airbags',
      label: 'Advanced airbag systems',
      description: 'Adaptive airbags deploy to cushion occupants.',
      type: 'mitigative',
      effectiveness: 'high',
      consequenceId: 'consequence-internal-impact',
    },
    {
      id: 'barrier-emergency-response',
      label: 'Rapid emergency response',
      description: 'Emergency services notified immediately via telematics.',
      type: 'mitigative',
      effectiveness: 'medium',
      consequenceId: 'consequence-rollover',
    },
    {
      id: 'barrier-crash-attenuators',
      label: 'Crash attenuator infrastructure',
      description: 'Highway barriers reduce impact severity with fixed objects.',
      type: 'mitigative',
      effectiveness: 'medium',
      consequenceId: 'consequence-fixed-object',
    },
  ],
};

