import type { Barrier } from './types';

export const mitigativeBarriers: Barrier[] = [
  {
    id: 'barrier-forward-collision-defensive-driving',
    label: 'Forward Collision Warning System and Defensive Driving',
    description:
      'Onboard collision warning tech and trained defensive maneuvers keep the vehicle aligned and bleed off speed before impact.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-fixed-object',
    mechanism: 'hybrid',
    owner: 'Supervisor',
  },
  {
    id: 'barrier-crumble-zone',
    label: 'Crumble Zone',
    description: 'Engineered crumple structures absorb crash forces before they reach the cab.',
    type: 'mitigative',
    effectiveness: 'medium',
    consequenceId: 'consequence-fixed-object',
    mechanism: 'passiveHardware',
    owner: 'EN Engineer',
  },
  {
    id: 'barrier-driver-restraints',
    label: 'Seatbelt prevents driver from colliding with the internals',
    description: 'Integrated seatbelts keep drivers from striking vehicle interiors even at high-speed impacts.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-driver-impact',
    mechanism: 'passiveHardware',
    owner: 'Engineering Manager',
  },
  {
    id: 'barrier-airbag-system',
    label: 'Airbag',
    description: 'Cab airbags deploy to cushion occupants from the dashboard and steering column.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-driver-impact',
    mechanism: 'passiveHardware',
    owner: 'Engineering Manager',
  },
  {
    id: 'barrier-rollover-protection',
    label: 'Rollover protection (reinforced structure)',
    description: 'Reinforced cabs and side structures keep the vehicle occupant space intact during roll-over events.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-rollover',
    mechanism: 'passiveHardware',
    owner: 'Engineering Manager',
  },
];
