import type { Barrier } from './types';

export const mitigativeBarriers: Barrier[] = [
  {
    id: 'barrier-forward-collision-defensive-driving',
    label: 'Forward Collision Warning System and Defensive Driving',
    description:
      'Onboard collision warning tech and trained defensive maneuvers keep the vehicle aligned and bleed off speed before impact.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-fixed-object',
    mechanism: 'hybrid',
    owner: 'Supervisor',
  },
  {
    id: 'barrier-crumble-zone',
    label: 'Crumble Zone',
    description: 'Engineered crumple structures absorb crash forces before they reach the cab.',
    type: 'mitigative',
    effectiveness: 'medium',
    consequenceId: 'consequence-fixed-object',
    mechanism: 'passiveHardware',
    owner: 'EN Engineer',
  },
  {
    id: 'barrier-driver-restraints',
    label: 'Driver restraint program',
    description: 'Seatbelt interlocks and compliance audits keep occupants restrained.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-driver-impact',
    mechanism: 'activeHardware',
    owner: 'Fleet Safety Manager',
  },
  {
    id: 'barrier-airbag-system',
    label: 'Adaptive airbag systems',
    description: 'Multi-stage airbags deploy to cushion cockpit impacts.',
    type: 'mitigative',
    effectiveness: 'high',
    consequenceId: 'consequence-driver-impact',
    mechanism: 'activeHardware',
    owner: 'Vehicle Engineering',
  },
  {
    id: 'barrier-rollover-response',
    label: 'Rollover rapid response plan',
    description: 'Automatic incident alerting dispatches emergency services and hazmat teams.',
    type: 'mitigative',
    effectiveness: 'medium',
    consequenceId: 'consequence-rollover',
    mechanism: 'hybrid',
    owner: 'Emergency Coordinator',
  },
];
