import type { Barrier } from './types';

export const preventiveBarriers: Barrier[] = [
  {
    id: 'barrier-driver-self-report',
    label: 'Driver reports impairment and supervisor assigns relief driver',
    description: 'Drivers self-assess condition before departure and request a replacement.',
    type: 'preventive',
    effectiveness: 'medium',
    threatId: 'threat-intoxicated-driving',
    mechanism: 'activeHuman',
    owner: 'Supervisor',
  },
  {
    id: 'barrier-dispatch-detection',
    label: 'Dispatch detects impairment during check-in',
    description: 'Operations manager conducts wellness checks before shift assignments.',
    type: 'preventive',
    effectiveness: 'high',
    threatId: 'threat-intoxicated-driving',
    mechanism: 'activeHuman',
    owner: 'Operations Manager',
  },
  {
    id: 'barrier-ignition-interlock',
    label: 'Ignition interlock prevents impaired start',
    description: 'Vehicle ignition only enables after driver passes onboard sobriety test.',
    type: 'preventive',
    effectiveness: 'high',
    threatId: 'threat-intoxicated-driving',
    mechanism: 'activeHardware',
    owner: 'Engineering Manager',
  },
  {
    id: 'barrier-lane-departure-alert',
    label: 'Lane-departure alerts escalate to supervisor',
    description:
      'Driver receives warnings from lane departure system, and supervisor is alerted if the driver ignores them.',
    type: 'preventive',
    effectiveness: 'medium',
    threatId: 'threat-intoxicated-driving',
    mechanism: 'hybrid',
    owner: 'Safety Supervisor',
  },
  {
    id: 'barrier-distraction-coaching',
    label: 'In-cab distraction coaching',
    description: 'Onboard camera analytics notify coach who provides immediate feedback to driver.',
    type: 'preventive',
    effectiveness: 'medium',
    threatId: 'threat-distracted-driving',
    mechanism: 'hybrid',
    owner: 'Driver Coach',
  },
  {
    id: 'barrier-surface-monitoring',
    label: 'Road surface monitoring bulletin',
    description: 'Operations issues traction alerts and mandatory speed adjustments for slippery routes.',
    type: 'preventive',
    effectiveness: 'medium',
    threatId: 'threat-slippery-road',
    mechanism: 'activeHuman',
    owner: 'Route Planner',
  },
  {
    id: 'barrier-visibility-protocol',
    label: 'Low-visibility protocol',
    description: 'Requires convoy escort and reduced speed when visibility drops below threshold.',
    type: 'preventive',
    effectiveness: 'medium',
    threatId: 'threat-poor-visibility',
    mechanism: 'activeHuman',
    owner: 'Shift Supervisor',
  },
];

